           main: main.ms
          title: GameDraftWithTextView
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core sqlite game2d graphics uix-skin uix
    orientation: portrait
 remote-console: 
        version: 1.1
