           main: main.ms
          title: GameCenter
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core uix uix-skin media graphics net
    orientation: portrait
 remote-console: 192.168.1.105:4321
        version: 1.0
