           main: main.ms
          title: GameDraftWithTextView
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core uix uix-skin sqlite game2d graphics
    orientation: portrait
 remote-console: 
        version: 1.1
