           main: main.ms
          title: FaceBook
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core game2d graphics media uix uix-skin
    orientation: portrait
 remote-console: 
        version: 1.0
