           main: main.ms
          title: FaceBook
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core graphics game2d media uix-skin uix
    orientation: portrait
 remote-console: 
        version: 1.0
