           main: main.ms
          title: GameCenter
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core game2d graphics media net uix
    orientation: portrait
 remote-console: 
        version: 1.0
