           main: main.ms
          title: TextShadow
    description: 
         author: Generated by Moscrif-Ide
      copyright: 
       homepage: 
           uses: core ui uix uix-skin media sqlite net game2d crypto box2d graphics sensor
    orientation: portrait
 remote-console: 
        version: 1.0
